// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'5a3e234946d6eee302eb658750cecab590483b8fa06822da92a1499fa673777c'>;
export type ExecutionHash =
  ExecutionHashBase<'f3b193012d181b0fadf96e786214a3294a692d90598fd45c3023b906d03f5bbd'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Buyer: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Listing: {
      readonly category: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly price_minor: CodecTypes['pg/int4@1']['output'];
      readonly quantity_available: CodecTypes['pg/int4@1']['output'];
      readonly seller_id: CodecTypes['pg/uuid@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Order: {
      readonly buyer_id: CodecTypes['pg/uuid@1']['output'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly idempotency_key: CodecTypes['pg/text@1']['output'];
      readonly status: 'PENDING' | 'PROCESSING' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED';
      readonly total_amount_minor: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly OrderItem: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly listing_id: CodecTypes['pg/uuid@1']['output'];
      readonly order_id: CodecTypes['pg/uuid@1']['output'];
      readonly price_at_purchase_minor: CodecTypes['pg/int4@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Review: {
      readonly buyer_id: CodecTypes['pg/uuid@1']['output'];
      readonly comment: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly listing_id: CodecTypes['pg/uuid@1']['output'];
      readonly rating: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Seller: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly store_name: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Buyer: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Listing: {
      readonly category: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly price_minor: CodecTypes['pg/int4@1']['input'];
      readonly quantity_available: CodecTypes['pg/int4@1']['input'];
      readonly seller_id: CodecTypes['pg/uuid@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Order: {
      readonly buyer_id: CodecTypes['pg/uuid@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly idempotency_key: CodecTypes['pg/text@1']['input'];
      readonly status: 'PENDING' | 'PROCESSING' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED';
      readonly total_amount_minor: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly OrderItem: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly listing_id: CodecTypes['pg/uuid@1']['input'];
      readonly order_id: CodecTypes['pg/uuid@1']['input'];
      readonly price_at_purchase_minor: CodecTypes['pg/int4@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Review: {
      readonly buyer_id: CodecTypes['pg/uuid@1']['input'];
      readonly comment: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly listing_id: CodecTypes['pg/uuid@1']['input'];
      readonly rating: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Seller: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly store_name: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Buyer: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Listing: {
      readonly category: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly price_minor: CodecTypes['pg/int4@1']['output'];
      readonly quantity_available: CodecTypes['pg/int4@1']['output'];
      readonly seller_id: CodecTypes['pg/uuid@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Order: {
      readonly buyer_id: CodecTypes['pg/uuid@1']['output'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly idempotency_key: CodecTypes['pg/text@1']['output'];
      readonly status: 'PENDING' | 'PROCESSING' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED';
      readonly total_amount_minor: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly OrderItem: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly listing_id: CodecTypes['pg/uuid@1']['output'];
      readonly order_id: CodecTypes['pg/uuid@1']['output'];
      readonly price_at_purchase_minor: CodecTypes['pg/int4@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Review: {
      readonly buyer_id: CodecTypes['pg/uuid@1']['output'];
      readonly comment: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly listing_id: CodecTypes['pg/uuid@1']['output'];
      readonly rating: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Seller: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly store_name: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Buyer: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Listing: {
      readonly category: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly price_minor: CodecTypes['pg/int4@1']['input'];
      readonly quantity_available: CodecTypes['pg/int4@1']['input'];
      readonly seller_id: CodecTypes['pg/uuid@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Order: {
      readonly buyer_id: CodecTypes['pg/uuid@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly idempotency_key: CodecTypes['pg/text@1']['input'];
      readonly status: 'PENDING' | 'PROCESSING' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED';
      readonly total_amount_minor: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly OrderItem: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly listing_id: CodecTypes['pg/uuid@1']['input'];
      readonly order_id: CodecTypes['pg/uuid@1']['input'];
      readonly price_at_purchase_minor: CodecTypes['pg/int4@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Review: {
      readonly buyer_id: CodecTypes['pg/uuid@1']['input'];
      readonly comment: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly listing_id: CodecTypes['pg/uuid@1']['input'];
      readonly rating: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Seller: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly store_name: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Buyer = {
    created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    email: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    orders: public_Order[];
    reviews: public_Review[];
    readonly [RelationKeys]?: 'orders' | 'reviews';
  };
  export type public_Listing = {
    category: CodecTypes['pg/text@1']['output'] | null;
    created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    currency: CodecTypes['pg/text@1']['output'];
    deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    description: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/uuid@1']['output'];
    price_minor: CodecTypes['pg/int4@1']['output'];
    quantity_available: CodecTypes['pg/int4@1']['output'];
    seller_id: CodecTypes['pg/uuid@1']['output'];
    title: CodecTypes['pg/text@1']['output'];
    updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    order_items: public_OrderItem[];
    reviews: public_Review[];
    seller: public_Seller;
    readonly [RelationKeys]?: 'order_items' | 'reviews' | 'seller';
  };
  export type public_Order = {
    buyer_id: CodecTypes['pg/uuid@1']['output'];
    created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    currency: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    idempotency_key: CodecTypes['pg/text@1']['output'];
    status: 'PENDING' | 'PROCESSING' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED';
    total_amount_minor: CodecTypes['pg/int4@1']['output'];
    updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    buyer: public_Buyer;
    order_items: public_OrderItem[];
    readonly [RelationKeys]?: 'buyer' | 'order_items';
  };
  export type public_OrderItem = {
    created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    currency: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    listing_id: CodecTypes['pg/uuid@1']['output'];
    order_id: CodecTypes['pg/uuid@1']['output'];
    price_at_purchase_minor: CodecTypes['pg/int4@1']['output'];
    quantity: CodecTypes['pg/int4@1']['output'];
    updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    listing: public_Listing;
    order: public_Order;
    readonly [RelationKeys]?: 'listing' | 'order';
  };
  export type public_Review = {
    buyer_id: CodecTypes['pg/uuid@1']['output'];
    comment: CodecTypes['pg/text@1']['output'] | null;
    created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    id: CodecTypes['pg/uuid@1']['output'];
    listing_id: CodecTypes['pg/uuid@1']['output'];
    rating: CodecTypes['pg/int4@1']['output'];
    updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    buyer: public_Buyer;
    listing: public_Listing;
    readonly [RelationKeys]?: 'buyer' | 'listing';
  };
  export type public_Seller = {
    created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    deleted_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    email: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    store_name: CodecTypes['pg/text@1']['output'];
    updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    listings: public_Listing[];
    readonly [RelationKeys]?: 'listings';
  };
}

export declare const models: {
  public: {
    Buyer: Models.public_Buyer;
    Listing: Models.public_Listing;
    Order: Models.public_Order;
    OrderItem: Models.public_OrderItem;
    Review: Models.public_Review;
    Seller: Models.public_Seller;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Buyer: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Buyer_email_key';
                  readonly columns: readonly ['email'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly Listing: {
              columns: {
                readonly category: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly currency: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly price_minor: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly quantity_available: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly seller_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Listing_category_created_at_idx';
                  readonly columns: readonly ['category', 'created_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Listing_seller_id_idx';
                  readonly columns: readonly ['seller_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Listing';
                    readonly columns: readonly ['seller_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Seller';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Order: {
              columns: {
                readonly buyer_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly currency: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly idempotency_key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'OrderStatus';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'OrderStatus' };
                };
                readonly total_amount_minor: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Order_buyer_id_created_at_idx';
                  readonly columns: readonly ['buyer_id', 'created_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Order_idempotency_key_key';
                  readonly columns: readonly ['idempotency_key'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Order';
                    readonly columns: readonly ['buyer_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Buyer';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly OrderItem: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly currency: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly listing_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly order_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly price_at_purchase_minor: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'OrderItem_order_id_listing_id_idx';
                  readonly columns: readonly ['order_id', 'listing_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'OrderItem';
                    readonly columns: readonly ['order_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Order';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'OrderItem';
                    readonly columns: readonly ['listing_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Listing';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Review: {
              columns: {
                readonly buyer_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly comment: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly listing_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly rating: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Review_buyer_id_listing_id_key';
                  readonly columns: readonly ['buyer_id', 'listing_id'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Review';
                    readonly columns: readonly ['buyer_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Buyer';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Review';
                    readonly columns: readonly ['listing_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Listing';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Seller: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly store_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Seller_email_key';
                  readonly columns: readonly ['email'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly OrderStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'PENDING',
                'PROCESSING',
                'SHIPPED',
                'DELIVERED',
                'CANCELLED',
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Buyer: { readonly namespace: 'public' & NamespaceId; readonly model: 'Buyer' };
    readonly Listing: { readonly namespace: 'public' & NamespaceId; readonly model: 'Listing' };
    readonly Order: { readonly namespace: 'public' & NamespaceId; readonly model: 'Order' };
    readonly OrderItem: { readonly namespace: 'public' & NamespaceId; readonly model: 'OrderItem' };
    readonly Review: { readonly namespace: 'public' & NamespaceId; readonly model: 'Review' };
    readonly Seller: { readonly namespace: 'public' & NamespaceId; readonly model: 'Seller' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Buyer: {
            readonly fields: {
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly deleted_at: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly orders: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['buyer_id'];
                };
              };
              readonly reviews: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Review';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['buyer_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Buyer';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly created_at: { readonly column: 'created_at' };
                readonly deleted_at: { readonly column: 'deleted_at' };
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Listing: {
            readonly fields: {
              readonly category: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly currency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly deleted_at: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly price_minor: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quantity_available: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly seller_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly order_items: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'OrderItem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['listing_id'];
                };
              };
              readonly reviews: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Review';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['listing_id'];
                };
              };
              readonly seller: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Seller';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['seller_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Listing';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly category: { readonly column: 'category' };
                readonly created_at: { readonly column: 'created_at' };
                readonly currency: { readonly column: 'currency' };
                readonly deleted_at: { readonly column: 'deleted_at' };
                readonly description: { readonly column: 'description' };
                readonly id: { readonly column: 'id' };
                readonly price_minor: { readonly column: 'price_minor' };
                readonly quantity_available: { readonly column: 'quantity_available' };
                readonly seller_id: { readonly column: 'seller_id' };
                readonly title: { readonly column: 'title' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Order: {
            readonly fields: {
              readonly buyer_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly currency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly idempotency_key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'OrderStatus' };
                };
              };
              readonly total_amount_minor: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly buyer: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Buyer';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['buyer_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly order_items: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'OrderItem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['order_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Order';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly buyer_id: { readonly column: 'buyer_id' };
                readonly created_at: { readonly column: 'created_at' };
                readonly currency: { readonly column: 'currency' };
                readonly id: { readonly column: 'id' };
                readonly idempotency_key: { readonly column: 'idempotency_key' };
                readonly status: { readonly column: 'status' };
                readonly total_amount_minor: { readonly column: 'total_amount_minor' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
          readonly OrderItem: {
            readonly fields: {
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly currency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly listing_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly order_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly price_at_purchase_minor: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly listing: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Listing';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['listing_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly order: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['order_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'OrderItem';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly created_at: { readonly column: 'created_at' };
                readonly currency: { readonly column: 'currency' };
                readonly id: { readonly column: 'id' };
                readonly listing_id: { readonly column: 'listing_id' };
                readonly order_id: { readonly column: 'order_id' };
                readonly price_at_purchase_minor: { readonly column: 'price_at_purchase_minor' };
                readonly quantity: { readonly column: 'quantity' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Review: {
            readonly fields: {
              readonly buyer_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly comment: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly deleted_at: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly listing_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly rating: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly buyer: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Buyer';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['buyer_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly listing: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Listing';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['listing_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Review';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly buyer_id: { readonly column: 'buyer_id' };
                readonly comment: { readonly column: 'comment' };
                readonly created_at: { readonly column: 'created_at' };
                readonly deleted_at: { readonly column: 'deleted_at' };
                readonly id: { readonly column: 'id' };
                readonly listing_id: { readonly column: 'listing_id' };
                readonly rating: { readonly column: 'rating' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Seller: {
            readonly fields: {
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly deleted_at: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly store_name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly listings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Listing';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['seller_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Seller';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly created_at: { readonly column: 'created_at' };
                readonly deleted_at: { readonly column: 'deleted_at' };
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly store_name: { readonly column: 'store_name' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'updated_at';
            readonly namespace: 'public';
            readonly table: 'Buyer';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'updated_at';
            readonly namespace: 'public';
            readonly table: 'Listing';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'updated_at';
            readonly namespace: 'public';
            readonly table: 'Order';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'updated_at';
            readonly namespace: 'public';
            readonly table: 'OrderItem';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'updated_at';
            readonly namespace: 'public';
            readonly table: 'Review';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'updated_at';
            readonly namespace: 'public';
            readonly table: 'Seller';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
